name: stickbridge
description: "Stick Bridge Cross - A never-ending arcade game built in Flutter + Flame."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Game engine & visuals
  flame: ^1.29.0
  flame_audio: ^2.11.6
  flutter_hooks: ^0.21.2

  # Ads and monetization
  google_mobile_ads: ^6.0.0

  # Optional animation tools
  rive: ^0.13.2

  # Icon support
  cupertino_icons: ^1.0.8

  # Logging for debug
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sfx/
    - assets/music/
    - assets/fonts/

  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
